[build]
base = "frontend"
command = "true"
publish = "."

[[redirects]]
from = "/pages/customer/checkout.php"
to = "/pages/customer/checkout.html"
status = 301
force = true

[[redirects]]
from = "/"
to = "/src/index.html"
status = 200

[[redirects]]
from = "/index.html"
to = "/src/index.html"
status = 200
