<?php
define('APP_ENV', getenv('APP_ENV') ?: 'development');
define('DB_HOST', getenv('DB_HOST') ?: (getenv('MYSQLHOST') ?: 'localhost'));
define('DB_PORT', getenv('DB_PORT') ?: (getenv('MYSQLPORT') ?: '3306'));
define('DB_NAME', getenv('DB_NAME') ?: (getenv('MYSQLDATABASE') ?: (APP_ENV === 'production' ? '' : 'foodbyk')));
define('DB_USER', getenv('DB_USER') ?: (getenv('MYSQLUSER') ?: (APP_ENV === 'production' ? '' : 'root')));
define('DB_PASS', getenv('DB_PASS') ?: (getenv('MYSQLPASSWORD') ?: ''));
define('DB_SSL_CA', getenv('DB_SSL_CA') ?: '');
define('AWS_ENDPOINT_URL', getenv('AWS_ENDPOINT_URL') ?: '');
define('AWS_DEFAULT_REGION', getenv('AWS_DEFAULT_REGION') ?: 'auto');
define('AWS_S3_BUCKET_NAME', getenv('AWS_S3_BUCKET_NAME') ?: '');
define('AWS_ACCESS_KEY_ID', getenv('AWS_ACCESS_KEY_ID') ?: '');
define('AWS_SECRET_ACCESS_KEY', getenv('AWS_SECRET_ACCESS_KEY') ?: '');
define('PAYMENT_TOKEN_ENCRYPTION_KEY', getenv('PAYMENT_TOKEN_ENCRYPTION_KEY') ?: '');
define('PAYFAST_MERCHANT_ID', getenv('PAYFAST_MERCHANT_ID') ?: '');
define('PAYFAST_MERCHANT_KEY', getenv('PAYFAST_MERCHANT_KEY') ?: '');
define('PAYFAST_RETURN_URL', getenv('PAYFAST_RETURN_URL') ?: '');
define('PAYFAST_CANCEL_URL', getenv('PAYFAST_CANCEL_URL') ?: '');
define('PAYFAST_NOTIFY_URL', getenv('PAYFAST_NOTIFY_URL') ?: '');
define('PAYFAST_SANDBOX', getenv('PAYFAST_SANDBOX') ?: '');
define('PAYFAST_PASSPHRASE', getenv('PAYFAST_PASSPHRASE') ?: '');
define('FRONTEND_URL', getenv('FRONTEND_URL') ?: '');
define('RESEND_API_KEY', getenv('RESEND_API_KEY') ?: '');
define('TWILIO_SID', getenv('TWILIO_SID') ?: '');
define('TWILIO_AUTH_TOKEN', getenv('TWILIO_AUTH_TOKEN') ?: '');
define('TWILIO_FROM_NUMBER', getenv('TWILIO_FROM_NUMBER') ?: '');
define('TWILIO_TEMPLATE_STAFF_NEW_ORDER', getenv('TWILIO_TEMPLATE_STAFF_NEW_ORDER') ?: '');
define('TWILIO_TEMPLATE_CUSTOMER_CONFIRMED', getenv('TWILIO_TEMPLATE_CUSTOMER_CONFIRMED') ?: '');
define('TWILIO_TEMPLATE_CUSTOMER_DECLINED', getenv('TWILIO_TEMPLATE_CUSTOMER_DECLINED') ?: '');
define('TWILIO_TEMPLATE_CUSTOMER_PAID', getenv('TWILIO_TEMPLATE_CUSTOMER_PAID') ?: '');
define('TWILIO_TEMPLATE_CUSTOMER_PAYMENT_FAILED', getenv('TWILIO_TEMPLATE_CUSTOMER_PAYMENT_FAILED') ?: '');
